version: "3"

services:
  web:
    container_name: server-plantdiseaes
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn app.main:app --reload --port=$PORT --host=server-plantdiseaes"
    ports:
      - 8000:8000
    env_file:
      - .env
